### ISSUE TITLE
[request] add flood levels to the forecast plot

### ISSUE THREAD

**Issue by fbaffie** [fbaffie/Flood_forecasting#9]
Elin to find out which values to use for mean annual flood and 5-year flood

**Comment by ElinLangsholt** [comment]
A file with flood values is here:

hdata\drift\flom\usikkerhet_grd\ut_test\flomtabell.rap

The following data are on the file:
station name, station number, Qm(obs), Q5(obs), Q50(obs), Qm(sim), Q5(sim), Q50(sim), area
